In [1]:
import requests


import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

## configs

In [2]:
ticker = "TSLA"

# Income statement

In [3]:
# create instance
tsla = yf.Ticker("TSLA")

In [9]:
tsla.get_financials()

,2021-12-31,2020-12-31,2019-12-31,2018-12-31
Research Development,2593000000.0,1491000000.0,1343000000.0,1460000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,6343000000.0,1154000000.0,-665000000.0,-1005000000.0
Minority Interest,1394000000.0,1454000000.0,1492000000.0,1390000000.0
Net Income,5519000000.0,721000000.0,-862000000.0,-976000000.0
Selling General Administrative,4517000000.0,3188000000.0,2646000000.0,2835000000.0
Gross Profit,13606000000.0,6630000000.0,4069000000.0,4042000000.0
Ebit,6523000000.0,1951000000.0,80000000.0,-253000000.0
Operating Income,6523000000.0,1951000000.0,80000000.0,-253000000.0
Other Operating Expenses,-27000000.0,-27000000.0,-27000000.0,-27000000.0
Interest Expense,-358000000.0,-784000000.0,-725000000.0,-653000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,699000000.0,292000000.0,110000000.0,58000000.0
Total Revenue,53823000000.0,31536000000.0,24578000000.0,21461000000.0
Total Operating Expenses,47300000000.0,29585000000.0,24498000000.0,21714000000.0
Cost Of Revenue,40217000000.0,24906000000.0,20509000000.0,17419000000.0
Total Other Income Expense Net,-180000000.0,-797000000.0,-745000000.0,-752000000.0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,5644000000.0,862000000.0,-775000000.0,-1063000000.0
Net Income Applicable To Common Shares,5524000000.0,690000000.0,-870000000.0,-976000000.0

In [6]:
tsla.financials

,2021-12-31,2020-12-31,2019-12-31,2018-12-31
Research Development,2593000000.0,1491000000.0,1343000000.0,1460000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,6343000000.0,1154000000.0,-665000000.0,-1005000000.0
Minority Interest,1394000000.0,1454000000.0,1492000000.0,1390000000.0
Net Income,5519000000.0,721000000.0,-862000000.0,-976000000.0
Selling General Administrative,4517000000.0,3188000000.0,2646000000.0,2835000000.0
Gross Profit,13606000000.0,6630000000.0,4069000000.0,4042000000.0
Ebit,6523000000.0,1951000000.0,80000000.0,-253000000.0
Operating Income,6523000000.0,1951000000.0,80000000.0,-253000000.0
Other Operating Expenses,-27000000.0,-27000000.0,-27000000.0,-27000000.0
Interest Expense,-358000000.0,-784000000.0,-725000000.0,-653000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,699000000.0,292000000.0,110000000.0,58000000.0
Total Revenue,53823000000.0,31536000000.0,24578000000.0,21461000000.0
Total Operating Expenses,47300000000.0,29585000000.0,24498000000.0,21714000000.0
Cost Of Revenue,40217000000.0,24906000000.0,20509000000.0,17419000000.0
Total Other Income Expense Net,-180000000.0,-797000000.0,-745000000.0,-752000000.0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,5644000000.0,862000000.0,-775000000.0,-1063000000.0
Net Income Applicable To Common Shares,5524000000.0,690000000.0,-870000000.0,-976000000.0

In [ ]:
revenue = {}
interest_expense = {}
income_before_tax = {}
income_tax_expense = {}
net_income = {}

Way to implement First lambda

1. Using Financial Model Prep 
2. Create helper function that helps you make a request based on set number of times